### PR TITLE
Tidy up C++ source

### PR DESCRIPTION
**Pull request by virgesmith**

### CODE REVIEW

**Comment by mpadge** [comment]
Thanks so much for your brilliant work @virgesmith! You've done a great job of tidying several of my formerly sloppily programmed bits - sorry if it left you scratching you head at times wondering why i'd done what. Passing strings by value? What the heck was I thinking! Other than the need to remove the flags from `Makevars.in`, I can't see any potential conflicts in what you've done, and so now remains only the primary question: How involved would you like to be in ongoing development? Please let me know, and I'll gladly sketch up a short TODO list.

I'd also appreciate your insights to the first Q under `src/get-lines.cpp`

Some more specific comments:

## General comments
1. Flags for `Makevars.in` get passed from `configure` (manual flags cause `check` to fail, as you can see [here at line#1251](https://travis-ci.org/osmdatar/osmdatar/builds/166228034)), but even then this 
   does not need the `-std=C++11` flag, because that's done in `DESCRIPTION`
2. I also don't use `-Wall` and `-Werror` because they are g++-specific

## `src/get-lines.cpp`:
1. I'm not sure why you've created the pointers `xmlways` and `xmlnodes` (lines#40-41) - `xml` is part of the Class def, so all members are passed by reference at all times. Why not retain direct refs to `xml.ways` and `xml.nodes` throughout?
2. The `reserve` of `wi->nodes` (line#108-109) is a great idea - I hadn't thought of that!
3. Thanks for tidying up my manual min-max with `std::min` etc - I had been meaning to do that.
4. Lines#172-177: Replacing `std::find` with find in container is definitely better.

## `src/get-lines.h`:
1. Lines#11-12: Replacing `boost::_map` with `std::_map` is important - thanks
2. Line#168: Replacing object copy with reference to `rway` (and equivalent in `get-points`): thanks

## `src/get-polygons.cpp`:
1. Line#54 `xml.polys.begin()` -> `xml.polys().begin()`: Sorry about that, and thanks!

## `src/get-polygons.h`:
1. Line#150: `swap` is much neater than my former manual iterator: thanks

## tests

Thanks for inserting these, and they'll stay for the moment, but all tests have to be reconstructed to avoid simple `skip_on_cran` and `skip_on_travis` use. [See here](https://discuss.ropensci.org/t/best-practices-for-testing-api-packages/460)

## TODO:
1. Re-align `{ varnames.insert }` instances?
2. Shift variable definitions back to start of code, not within (`ni`, `lon`, `lat`, etc.)

**Comment by virgesmith** [comment]
Mark,

Thanks and no problems, yes happy to be involved in ongoing development 
as time permits.

As for those const refs in lines 40-41 on get-lines.cpp they're not 
strictly necessary just means you have to type a little less and you 
force the compiler to only call the accessors once. The optimiser will 
probably do this anyway though, so definitely optional.

On your TODO, slightly surprised you want to declare all vars at the 
start of the function, this is very old-style C practice. These days its 
recommended you declare vars as close to the point of use as possible. 
There's no worry about declaring vars (scalar ones at least) inside 
loops as the compiler will just reuse. Also wondering what you mean re: 
"Re-align |{ varnames.insert }| instances?"

Re: the use of unordered containers over "normal" associative containers 
- I'd only recommend this if you can demonstrate that there's a 
  bottleneck with the normal container, and this is only likely if the 
  size gets very big. One problem with unordered containers is the 
  ordering - it's implementation specific - so if you rely (even for 
  tests) on the internal ordering in any way, you'll find it won't be the 
  same on different platforms.

Re: Makefile.in, I would highly recommend maxing out the warning level, 
I assume there's a way of providing compiler-specific flags?

I would specifically take a look at what I had to do in lines 91-92 of 
get-polygons.cpp - you need to bear in mind that map::operator[] is a 
non-const operation and will insert a (default-constructed) value with 
the key if it doesnt already exist. Since I made the map const I had to 
use find(), and saw it returned an invalid iterator (and crashed until I 
put the check in)

Cheers,

Andrew

PS to profile, I found this works:

R -d "valgrind --tool=callgrind" -f testthat.R

then view the results with

kcachegrind callgrind.out.<pid>

(assuming you're on linux of course). I did also get gdb to work in a 
clunky way by running the tests within Rstudio, quickly getting the pid 
of the R process and attaching gdb to the pid (gdb needed to be run as 
sudo).

**Comment by mpadge** [comment]
Thanks @virgesmith  for your reply and explanations. A couple of clarifications:

> Thanks and no problems, yes happy to be involved in ongoing development
> as time permits.

Awesome! The major issues are already open and awaiting input, especially #3  and #4. I'd be thrilled if you were to contribute as much as you can whenever you can!

> As for those const refs in lines 40-41 on get-lines.cpp they're not
> strictly necessary just means you have to type a little less and you
> force the compiler to only call the accessors once. The optimiser will
> probably do this anyway though, so definitely optional.

Okay, good to know. I wasn't sure whether you had some concrete reason for doing that, but am happy to leave things that way.

> On your TODO, slightly surprised you want to declare all vars at the
> start of the function, this is very old-style C practice. These days its
> recommended you declare vars as close to the point of use as possible.
> There's no worry about declaring vars (scalar ones at least) inside
> loops as the compiler will just reuse. 

Yeah, you found me out, but again happy to leave things the way you've got it now.

> Also wondering what you mean re:
> "Re-align |{ varnames.insert }| instances?"

Already done, just because i'm a stickler for vertical alignment of `{}` (with sensible exceptions).

> Re: the use of unordered containers over "normal" associative containers
> - I'd only recommend this if you can demonstrate that there's a
>   bottleneck with the normal container, and this is only likely if the
>   size gets very big. One problem with unordered containers is the
>   ordering - it's implementation specific - so if you rely (even for
>   tests) on the internal ordering in any way, you'll find it won't be the
>   same on different platforms.

They have to be unordered because OpenStreetMap has `long long` IDs, so hashes are necessary for efficient access. The actual ordering is never relevant, just the `long long` IDs. At the moment these are only really noticeable at Line#117 of `get-lines.h`, but they'll also play a further role in `get-polygons`, which is currently unfinished. In short: Take my word on this one, unordered containers are absolutely necessary here.

> Re: Makefile.in, I would highly recommend maxing out the warning level,
> I assume there's a way of providing compiler-specific flags?

It's officially disapproved, see [here](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars)

> I would specifically take a look at what I had to do in lines 91-92 of
> get-polygons.cpp - you need to bear in mind that map::operator[] is a
> non-const operation and will insert a (default-constructed) value with
> the key if it doesnt already exist. Since I made the map const I had to
> use find(), and saw it returned an invalid iterator (and crashed until I
> put the check in)

Would you be so kind as to open as issue on that, just so it's flagged for future reference?

> PS to profile, I found this works:
> 
> R -d "valgrind --tool=callgrind" -f testthat.R
> 
> then view the results with
> 
> kcachegrind callgrind.out.<pid>

That's really helpful, thanks! I never even thought of valgrinding an R call, but it works really well.

> (assuming you're on linux of course). I did also get gdb to work in a
> clunky way by running the tests within Rstudio, quickly getting the pid
> of the R process and attaching gdb to the pid (gdb needed to be run as
> sudo).

And i never thought to try that either. Annoying to have to do it that way, but potentially useful.

Thanks again for all the fabulous improvements,
mark

p.s. One further note: all github comments support markdown, and usage of such can greatly ease reading comments.

**Comment by virgesmith** [comment]
Mark

Been rather busy today but have just about finished some work I thought 
would take 2 days, so I'll get on the case tomorrow

Cheers,

Andrew

**Comment by virgesmith** [comment]
Hi Andrew,

I've just looked over some of those commits and it looks like a decent chunk of refactoring you've put in. Great work sir!

You may be interested to see the C++ section of the Efficient R Programming book I've written with Colin Gillespie, hence being keen to learn this seemingly most tricky and giant of languages.

Please take a look here: https://csgillespie.github.io/efficientR/performance.html#rcpp (that initial graph is mine!)

Look forward to using your data in due course: fits almost straight into research plans I have at LIDA. We should all meet up at some point BTW!

Robin

**Pull request merged**
