### PR TITLE
Link to BH for its xml_parser - maybe fixes #4

### LINKED ISSUE #4: replace boost dependency with rapidxml header

### PR DESCRIPTION
**Pull request by Robinlovelace**
Thanks to @jeroenooms for this - think it removes the boost dep. cc @hrbrmstr.

### CODE REVIEW

**Comment by hrbrmstr** [comment]
I was wondering if it was header only (I made the assumption it wasn't since it wasn't linked to in the pkg). If it's header only this **awesome** news. I can easily integrate the query builder, too, then. I'll try to test this later today.

**Comment by hrbrmstr** [comment]
I have another PR for this as well. Along with BH in the `LinkingTo` field, I added:

``` cpp
// [[Rcpp::depends(BH)]]
#include <vector>
```

into `common.h` for `clang` support (i.e. macOS). The Rcpp sugar for BH there prbly isn't 100% necessary but I use it when linking against `BH` in a cpl other Rcpp-backed packages of mine.

Also (again, for macOS) I had to (at least temporarily) change `configure` to:

``` bash
OS=`uname -s`

if [ "$OS" == "Darwin" ] ; then
  PKG_CXXFLAGS=""
  PKG_LIBS=""
else
  PKG_CXXFLAGS="-fprofile-arcs -ftest-coverage"
  PKG_LIBS="-lgcov"
fi
```

I can test it on Windows at some point this week (I'm just glad I had a conference call that I was not needed on to test this out).

**Comment by mpadge** [comment]
Thanks @Robinlovelace and @hrbrmstr!

I'm in the process of ditching the entire BH dependency and just including the [rapidxml](http://rapidxml.sourceforge.net/) header file. Should be done by sometime next week.

First job is proper multipolygon handling, which should be done this week.

**Comment by hrbrmstr** [comment]
Just lemme know what I can do to help. I can test on macOS & Windows and add in appveyor and travis checks for those as well as anything else you'd like.

**Comment by Robinlovelace** [comment]
Sounds good - looking forward to see rapidXML in action.

**Pull request merged**
